# Configuration Doctrine Migrations - BLOCAGE NOUVELLES MIGRATIONS
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    
    # PROTECTION: Empêche la génération automatique de migrations
    enable_profiler: false
    
    # FORCE: Utilisation uniquement d'InitialSchema.php
    all_or_nothing: true
    check_database_platform: false
    
    # SÉCURITÉ: Configuration verrouillée
    organize_migrations: false