# Configuration Doctrine Migrations - BLOCAGE NOUVELLES MIGRATIONS
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    
    # Configuration simple et fonctionnelle
    all_or_nothing: true
    check_database_platform: false
    organize_migrations: false
