when@dev:
    web_profiler:
        toolbar: false  # Désactivé pour performance
        intercept_redirects: false

    framework:
        profiler:
            enabled: false  # Désactivé pour performance
            collect_serializer_data: false

when@test:
    framework:
        profiler: { collect: false }
